# Generated by Django 5.1.1 on 2024-09-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_author",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_reader",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("author", "Author"), ("reader", "Reader")],
                default="reader",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
